package com.example.diaviseo.model.exercise

enum class ExerciseType(
    val typeId: Int,
    val nameEn: String,
    val nameKo: String,
    val category: String
) {
    OTHER_WORKOUT(0, "OTHER_WORKOUT", "기타 운동", "일반"),
    BADMINTON(2, "BADMINTON", "배드민턴", "구기 종목"),
    BASEBALL(4, "BASEBALL", "야구", "구기 종목"),
    BASKETBALL(5, "BASKETBALL", "농구", "구기 종목"),
    BIKING(8, "BIKING", "자전거 타기", "아웃도어"),
    BIKING_STATIONARY(9, "BIKING_STATIONARY", "실내 자전거", "유산소"),
    BOOT_CAMP(10, "BOOT_CAMP", "부트 캠프", "프리 웨이트"),
    BOXING(11, "BOXING", "권투", "일반"),
    CALISTHENICS(13, "CALISTHENICS", "맨몸 운동", "유산소"),
    CRICKET(14, "CRICKET", "크리켓", "구기 종목"),
    DANCING(16, "DANCING", "댄스", "일반"),
    ELLIPTICAL(25, "ELLIPTICAL", "일립티컬", "유산소"),
    EXERCISE_CLASS(26, "EXERCISE_CLASS", "운동 수업", "유산소"),
    FENCING(27, "FENCING", "펜싱", "구기 종목"),
    FOOTBALL_AMERICAN(28, "FOOTBALL_AMERICAN", "미식축구", "구기 종목"),
    FOOTBALL_AUSTRALIAN(29, "FOOTBALL_AUSTRALIAN", "호주식 축구", "구기 종목"),
    FRISBEE_DISC(31, "FRISBEE_DISC", "프리스비", "일반"),
    GOLF(32, "GOLF", "골프", "구기 종목"),
    GUIDED_BREATHING(33, "GUIDED_BREATHING", "호흡 운동", "일반"),
    GYMNASTICS(34, "GYMNASTICS", "체조", "일반"),
    HANDBALL(35, "HANDBALL", "핸드볼", "구기 종목"),
    HIGH_INTENSITY_INTERVAL_TRAINING(36, "HIGH_INTENSITY_INTERVAL_TRAINING", "고강도 인터벌 트레이닝", "유산소"),
    HIKING(37, "HIKING", "등산", "아웃도어"),
    ICE_HOCKEY(38, "ICE_HOCKEY", "아이스하키", "겨울 스포츠"),
    ICE_SKATING(39, "ICE_SKATING", "아이스 스케이팅", "겨울 스포츠"),
    MARTIAL_ARTS(44, "MARTIAL_ARTS", "무술", "일반"),
    PADDLING(46, "PADDLING", "패들링", "아웃도어"),
    PARAGLIDING(47, "PARAGLIDING", "패러글라이딩", "일반"),
    PILATES(48, "PILATES", "필라테스", "프리 웨이트"),
    RACQUETBALL(50, "RACQUETBALL", "라켓볼", "구기 종목"),
    ROCK_CLIMBING(51, "ROCK_CLIMBING", "암벽 등반", "아웃도어"),
    ROLLER_HOCKEY(52, "ROLLER_HOCKEY", "롤러 하키", "미분류"),
    ROWING(53, "ROWING", "조정", "수상스포츠"),
    ROWING_MACHINE(54, "ROWING_MACHINE", "조정 머신", "수상스포츠"),
    RUGBY(55, "RUGBY", "럭비", "구기 종목"),
    RUNNING(56, "RUNNING", "달리기", "유산소"),
    RUNNING_TREADMILL(57, "RUNNING_TREADMILL", "러닝머신", "유산소"),
    SAILING(58, "SAILING", "요트 타기", "수상스포츠"),
    SCUBA_DIVING(59, "SCUBA_DIVING", "스쿠버 다이빙", "수상스포츠"),
    SKATING(60, "SKATING", "스케이팅", "구기 종목"),
    SKIING(61, "SKIING", "스키", "겨울 스포츠"),
    SNOWBOARDING(62, "SNOWBOARDING", "스노보드", "겨울 스포츠"),
    SNOWSHOEING(63, "SNOWSHOEING", "스노 슈잉", "겨울 스포츠"),
    SOCCER(64, "SOCCER", "축구", "구기 종목"),
    SOFTBALL(65, "SOFTBALL", "소프트볼", "구기 종목"),
    SQUASH(66, "SQUASH", "스쿼시", "구기 종목"),
    STAIR_CLIMBING(68, "STAIR_CLIMBING", "계단 오르기", "유산소"),
    STAIR_CLIMBING_MACHINE(69, "STAIR_CLIMBING_MACHINE", "스텝머신", "유산소"),
    STRENGTH_TRAINING(70, "STRENGTH_TRAINING", "근력 운동", "프리 웨이트"),
    STRETCHING(71, "STRETCHING", "스트레칭", "프리 웨이트"),
    SURFING(72, "SURFING", "서핑", "수상스포츠"),
    SWIMMING_OPEN_WATER(73, "SWIMMING_OPEN_WATER", "오픈워터 수영", "수상스포츠"),
    SWIMMING_POOL(74, "SWIMMING_POOL", "수영장 수영", "수상스포츠"),
    TABLE_TENNIS(75, "TABLE_TENNIS", "탁구", "구기 종목"),
    TENNIS(76, "TENNIS", "테니스", "구기 종목"),
    VOLLEYBALL(78, "VOLLEYBALL", "배구", "구기 종목"),
    WALKING(79, "WALKING", "걷기", "유산소"),
    WATER_POLO(80, "WATER_POLO", "수구", "수상스포츠"),
    WEIGHTLIFTING(81, "WEIGHTLIFTING", "역도", "프리 웨이트"),
    WHEELCHAIR(82, "WHEELCHAIR", "휠체어 운동", "일반"),
    YOGA(83, "YOGA", "요가", "프리 웨이트");

    companion object {
        fun fromTypeId(typeId: Int): ExerciseType? = values().find { it.typeId == typeId }
    }
}
