package com.example.diaviseo.model.exercise

import com.example.diaviseo.R

val exerciseIconMap = mapOf(
    0 to R.drawable.ic_exercise_other_workout,
    11 to R.drawable.ic_exercise_boxing,
    16 to R.drawable.ic_exercise_dancing,
    31 to R.drawable.ic_exercise_frisbee_disc,
    34 to R.drawable.ic_exercise_gymnastics,
    33 to R.drawable.ic_exercise_guided_breathing,
    44 to R.drawable.ic_exercise_martial_arts,
    47 to R.drawable.ic_exercise_paragliding,
    82 to R.drawable.ic_exercise_wheelchair,
    9 to R.drawable.ic_exercise_biking_stationary,
    13 to R.drawable.ic_exercise_calisthenics,
    25 to R.drawable.ic_exercise_elliptical,
    26 to R.drawable.ic_exercise_exercise_class,
    36 to R.drawable.ic_exercise_high_intensity_interval_training,
    56 to R.drawable.ic_exercise_running,
    57 to R.drawable.ic_exercise_running_treadmill,
    68 to R.drawable.ic_exercise_stair_climbing,
    69 to R.drawable.ic_exercise_stair_climbing_machine,
    79 to R.drawable.ic_exercise_walking,
    10 to R.drawable.ic_exercise_boot_camp,
    48 to R.drawable.ic_exercise_pilates,
    70 to R.drawable.ic_exercise_strength_training,
    71 to R.drawable.ic_exercise_stretching,
    81 to R.drawable.ic_exercise_weightlifting,
    83 to R.drawable.ic_exercise_yoga,
    8 to R.drawable.ic_exercise_biking,
    37 to R.drawable.ic_exercise_hiking,
    46 to R.drawable.ic_exercise_paddling,
    51 to R.drawable.ic_exercise_rock_climbing,
    53 to R.drawable.ic_exercise_rowing,
    54 to R.drawable.ic_exercise_rowing_machine,
    58 to R.drawable.ic_exercise_sailing,
    59 to R.drawable.ic_exercise_scuba_diving,
    72 to R.drawable.ic_exercise_surfing,
    73 to R.drawable.ic_exercise_swimming_open_water,
    74 to R.drawable.ic_exercise_swimming_pool,
    80 to R.drawable.ic_exercise_water_polo,
    38 to R.drawable.ic_exercise_ice_hockey,
    39 to R.drawable.ic_exercise_ice_skating,
    61 to R.drawable.ic_exercise_skiing,
    62 to R.drawable.ic_exercise_snowboarding,
    63 to R.drawable.ic_exercise_snowshoeing,
    2 to R.drawable.ic_exercise_badminton,
    4 to R.drawable.ic_exercise_baseball,
    5 to R.drawable.ic_exercise_basketball,
    14 to R.drawable.ic_exercise_cricket,
    27 to R.drawable.ic_exercise_fencing,
    28 to R.drawable.ic_exercise_football_american,
    29 to R.drawable.ic_exercise_football_australian,
    32 to R.drawable.ic_exercise_golf,
    35 to R.drawable.ic_exercise_handball,
    50 to R.drawable.ic_exercise_racquetball,
    52 to R.drawable.ic_exercise_roller_hockey,
    55 to R.drawable.ic_exercise_rugby,
    60 to R.drawable.ic_exercise_skating,
    64 to R.drawable.ic_exercise_soccer,
    65 to R.drawable.ic_exercise_softball,
    66 to R.drawable.ic_exercise_squash,
    75 to R.drawable.ic_exercise_table_tennis,
    76 to R.drawable.ic_exercise_tennis,
    78 to R.drawable.ic_exercise_volleyball
)
